member_file_path = ''
member_dom = None
primitive_dict = {}
# Primitive=None
collective_dict = {}
# Collective=None
adviser_dict = {}
# Adviser=None
monitor_dict = {}
# Monitor=None
member_num = -1
# AAA=None
network_list = []